apiVersion: v1
kind: Service
metadata:
  name: mongo-node-port-service
spec:
  type: NodePort
  ports:
    - port: 3210
      targetPort: 27017
      nodePort: 31616
  selector:
    component: mongo      