apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    component: server
spec:
  containers:
    - name: server
      image: rksharma95/node-blog-app
      ports:
        - containerPort: 3000
      env:
      - name: SESSION_SECRET
        value: "topSECRET"  