version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_USER=mydbuser
      - MONGO_PASSWORD=mypass
    depends_on:
      - mongo  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mydbuser 
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
