# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: workflow_dispatch
  # push:
  #   branches: [ master ]
  #   paths:
  #     - /docker/docker-with-nodejs/**
  # pull_request:
  #   branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "docker/docker-with-nodejs"
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  docker_build_and_push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "docker/docker-with-nodejs"
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./docker/docker-with-nodejs/
        file: ./docker/docker-with-nodejs/Dockerfile.prod
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
